language: node_js
node_js:
  - '12'
  - '11'
  - '10'
  - '8'

before_script:
  - npm install
  - npm run build

script:
  - npm run test

jobs:
  include:
    - stage: npm release
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_API_KEY
        # prevent travis from cleaning build files
        skip_cleanup: true
        on:
          tags: true
    - stage: github release
      script: echo "Deploying to GitHub ..."
      script: npm pack
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        # enable wildcards
        file_glob: true
        file: 'unrepeat-*.tgz'
        skip_cleanup: true
        on:
          tags: true
    - stage: codecov upload
      script: npm test -- --coverage
      after_script: codecov --token=$CODECOV_TOKEN
