os: linux
language: node_js
node_js:
  - node
  - lts/*

script:
  - yarn test
  - yarn lint
  - yarn build

jobs:
  include:
    - stage: npm release
      script:
        - echo "Deploying to npm ..."
        - yarn build
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_API_KEY
        # prevent travis from cleaning build files
        skip_cleanup: true
        # on:
        #   tags: true
    - stage: github release
      script:
        - echo "Deploying to GitHub ..."
        - yarn build
        - yarn pack
      deploy:
        edge: true
        provider: releases
        api_key: $GITHUB_TOKEN
        # enable wildcards
        file_glob: true
        file: 'unrepeat-*.tgz'
        skip_cleanup: true
        on:
          tags: true
    - stage: codecov upload
      script: npm test -- --coverage
      after_script: codecov --token=$CODECOV_TOKEN
